### ISSUE TITLE
MVP tracking issue

### ISSUE THREAD

**Issue by tzdybal** [lazyledger/optimint#70]
- [ ] Generalized Data Availability Layer client API
    - [x] submission
    - [ ] availability check (#61)
    - [ ] data retrieval (#62)
- [ ] Mock DA layer (#63)
- [ ] LazyLedger DA layer implementation (#64)
- [ ] Transaction Aggregation (#69)
- [ ] Block propagation via DA layer (#68)
